name: Battery
main: com.tenjava.slipcor.TenJava
version: '${project.version}'
commands:
  battery:
    description: Place a special iron block that can be loaded with redstone current
    aliases: ['b']
    usage: |
      /<command>